<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.4" />
    <PackageReference Include="Buildalyzer" Version="9.0.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.6" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\shared\Fluence.Shared.MaterialIcons\MaterialIconTheme.cs" Link="MaterialIcons\MaterialIconTheme.cs" />
    <Content Include="..\..\third_party\material-icon-theme\dist\material-icons.json" Link="MaterialIcons\dist\material-icons.json" TargetPath="MaterialIcons\dist\material-icons.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\..\third_party\material-icon-theme\png\**\*.png" Link="MaterialIcons\png\%(RecursiveDir)%(Filename)%(Extension)" TargetPath="MaterialIcons\png\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Fluence.Core\Fluence.Core.csproj" />
  </ItemGroup>

</Project>
