<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.4" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Fluence.Core\Fluence.Core.csproj" />
    <ProjectReference Include="..\Fluence.Modules.DotnetCli\Fluence.Modules.DotnetCli.csproj" />
    <ProjectReference Include="..\Fluence.Modules.Debug\Fluence.Modules.Debug.csproj" />
    <ProjectReference Include="..\Fluence.Modules.LanguageServer\Fluence.Modules.LanguageServer.csproj" />
  </ItemGroup>
</Project>
