<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Fluence.Application\Fluence.Application.csproj" />
    <ProjectReference Include="..\Fluence.Core\Fluence.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Buildalyzer" Version="9.0.0" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.6" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
